### ISSUE TITLE
Item Pickup After Setting Price and clicking X

### ISSUE THREAD

**Issue by WickedHeroine** [Sourdough-Games/Pawn-Shop-Simulator#33]
After putting a phone on display, I clicked the price card to set the price then clicked X to exit and the phone got picked up again. 

https://github.com/Sourdough-Games/Pawn-Shop-Simulator/assets/166264143/8f6f1fcb-ca40-4d37-b980-a1a48d7af0a3

**Comment by JTDevil666** [comment]
Yeah, when you click on Set or X when you set the price, it pick up the item in the background again :) 
I experience this on all items that goes behind the UI when you set the price.
