### ISSUE TITLE
Clipping in corners on ultrawide screens

### ISSUE THREAD

**Issue by JTDevil666** [Sourdough-Games/Pawn-Shop-Simulator#35]
See picture - it's clipping in the corners on ultrawide screens.
This is on a 49" Samsung G9, where I stand in a corner in the shop.

![2024-04-12_22-11-07](https://github.com/Sourdough-Games/Pawn-Shop-Simulator/assets/166335457/93a93569-672a-4ed3-adee-c76be75bac83)

**Comment by GrumpyCrouton** [comment]
Leaving this open in case the issue persists. Let me know

**Comment by JTDevil666** [comment]
Seems to be fixed now :)
