### ISSUE TITLE
Exit Game button not working.

### ISSUE THREAD

**Issue by devin7821** [Sourdough-Games/Pawn-Shop-Simulator#42]
The image shows what happens when I hit the main menu exit button, menu just disappears.
![FailedToExit](https://github.com/Sourdough-Games/Pawn-Shop-Simulator/assets/121152485/a54c6712-71d2-4b5c-b9bc-30909477bf21)

**Comment by GrumpyCrouton** [comment]
At least you still get to watch that guy dance

**Comment by GrumpyCrouton** [comment]
Duplicate of #48
