### ISSUE TITLE
Click through UI resetting the price

### ISSUE THREAD

**Issue by JTDevil666** [Sourdough-Games/Pawn-Shop-Simulator#45]
When you are setting a price on the price tag and clicking on the price tag in the background, the price goes back to 0.

https://github.com/Sourdough-Games/Pawn-Shop-Simulator/assets/166335457/befb8c9a-0a8d-4320-8605-320e8b8adf5d

**Comment by JTDevil666** [comment]
More specific:
Clicking on the price tag sets the price to the last memorized value.
If no price is set, the value is 0 of course :)

**Comment by JTDevil666** [comment]
https://github.com/Sourdough-Games/Pawn-Shop-Simulator/assets/166335457/840f403f-e846-4052-ac32-e736a41c4021

**Comment by GrumpyCrouton** [comment]
Same issue as #46, closing this one
