### ISSUE TITLE
Click through esc menu UI

### ISSUE THREAD

**Issue by JTDevil666** [Sourdough-Games/Pawn-Shop-Simulator#46]
I'm able to click through the ESC menu UI, see video

https://github.com/Sourdough-Games/Pawn-Shop-Simulator/assets/166335457/6fe0b24a-34ad-4613-9037-7b2597f8759e

**Comment by GrumpyCrouton** [comment]
With the rewrite of the holding system, I also streamlined checking if the player is supposed to be able to click on objects, so I think this will be fixed in the next update with work I've already done.

**Comment by JTDevil666** [comment]
This issue is still persistent after new holding object logic.

**Comment by GrumpyCrouton** [comment]
What were you able to click through to?

**Comment by JTDevil666** [comment]
Only the car, nothing else.
Tested with all the items and the storage unit guy - I'm only able to click through the menu when the car is in the background.
End result is that I'm entering the car.
