### ISSUE TITLE
Storage Unit Doors looses highlight first after hovering over

### ISSUE THREAD

**Issue by JTDevil666** [Sourdough-Games/Pawn-Shop-Simulator#51]
Storage Unit Doors is highlighted at the top after buying the units.
Doesn't go away before you hover over it with the mouse again.
I guess the highlight should have been gone when door is fully open, or eventually never been highlighted in white? :) 

https://streamable.com/zfnte2

**Comment by GrumpyCrouton** [comment]
You are correct, the white highlight should only happen when looking at the door
